name: fintech_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aws-c-auth=0.9.3
  - aws-c-cal=0.9.13
  - aws-c-common=0.12.6
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.7
  - aws-c-http=0.10.7
  - aws-c-io=0.23.3
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.11.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.35.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.16.0
  - azure-storage-common-cpp=12.12.0
  - azure-storage-files-datalake-cpp=12.14.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - gflags=2.2.2
  - glog=0.7.1
  - icu=78.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libabseil=20250512.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libprotobuf=6.31.1
  - libre2-11=2025.11.05
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libthrift=0.22.0
  - libutf8proc=2.11.3
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - ncurses=6.5
  - nlohmann_json=3.12.0
  - numpy=2.0.2
  - openssl=3.6.0
  - orc=2.2.2
  - pandas=2.3.1
  - pip=25.2
  - prometheus-cpp=1.3.0
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - re2=2025.11.05
  - readline=8.3
  - s2n=1.6.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.7
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - packaging==26.0
      - pillow==11.3.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - propcache==0.4.1
      - psutil==7.2.1
      - pyparsing==3.3.2
      - pytorch-forecasting==1.4.0
      - pytorch-lightning==2.6.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.5.1+cu121
      - torch-cluster==1.6.3+pt25cu121
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt25cu121
      - torch-sparse==0.6.18+pt25cu121
      - torch-spline-conv==1.2.2+pt25cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - xgboost==2.1.4
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/jbs263/miniconda3/envs/fintech_gpu
